name: Deploy

'on':
  workflow_run:
    workflows: [ "Unit Tests" ]
    types: [ completed ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "deploy"
        run: echo "Run deployment script"
