name: Unit Tests

'on':
  workflow_run:
    workflows: [ "Build" ]
    types: [ completed ]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: "unit tests"
        run: echo "Run unit tests"
